name: "Install Clang (LLVM apt)"
description: "Install specific Clang version from apt.llvm.org based on Ubuntu codename."

inputs:
  version:
    description: "Clang major version (e.g. 19)"
    required: false
    default: "latest"
  supported_ubuntu_codenames:
    description: "Space-separated supported Ubuntu codenames (e.g. 'focal jammy noble')"
    required: false
    default: "focal jammy noble"

outputs:
  codename:
    description: "Ubuntu codename (from check-ubuntu)"
    value: ${{ steps.os.outputs.codename }}
  source:
    description: "Install source used: ubuntu or llvm"
    value: ${{ steps.decide.outputs.source }}
  clang_bin_name:
    value: "clang-${{ inputs.version }}"
  clangxx_bin_name:
    value: "clang++-${{ inputs.version }}"

runs:
  using: composite
  steps:
    - name: Check Ubuntu
      id: os
      uses: ./.github/actions/check-ubuntu

    - name: Show OS info (outputs example)
      shell: bash
      run: |
        echo "--- Show OS info ---"
        echo "id=${{ steps.os.outputs.id }}"
        echo "version_id=${{ steps.os.outputs.version_id }}"
        echo "codename=${{ steps.os.outputs.codename }}"

    # --- 共通依存 ---
    - name: Install base packages
      shell: bash
      run: |
        echo "--- Install base packages ---"
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg

    - name: Validate supported codename
      shell: bash
      run: |
        echo "--- Validate supported codename ---"
        set -euo pipefail
        c="${{ steps.os.outputs.codename }}"
        if ! grep -qw "$c" <<< "${{ inputs.supported_ubuntu_codenames }}"; then
          echo "::error::Unsupported Ubuntu codename: $c"
          echo "Supported: ${{ inputs.supported_ubuntu_codenames }}"
          exit 1
        fi

    - name: Decide install source (ubuntu repo or llvm.sh)
      id: decide
      shell: bash
      run: |
        echo "--- Decide install source (ubuntu repo or llvm.sh) ---"
        set -euo pipefail
        v="${{ inputs.version }}"

        # APT の現状構成で「実際にインストール可能か」を dry-run で判定する
        if sudo apt-get install -y -s "clang-${v}" "clang++-${v}" "lld-${v}" >/dev/null 2>&1; then
          echo "source=ubuntu" >> "$GITHUB_OUTPUT"
          echo "clang-${v}/lld-${v} are installable from current APT sources -> use ubuntu repo"
        else
          echo "source=llvm" >> "$GITHUB_OUTPUT"
          echo "clang-${v}/lld-${v} are NOT installable from current APT sources -> use llvm.sh"
        fi

    - name: Setup LLVM apt repo via llvm.sh (only if needed)
      if: ${{ steps.decide.outputs.source == 'llvm' }}
      shell: bash
      run: |
        echo "--- Setup LLVM apt repo via llvm.sh (only if needed) ---"
        set -euo pipefail
        v="${{ inputs.version }}"

        curl -fsSL https://apt.llvm.org/llvm.sh -o llvm.sh
        chmod +x llvm.sh

        # llvm.sh が Ubuntu codename 判定 + key/repo 設定を行う
        sudo ./llvm.sh "$v"

        # llvm.sh 実行後に index 更新されている想定だが、念のため
        sudo apt-get update

    - name: Install Clang
      shell: bash
      run: |
        echo "--- Install Clang ---"
        set -euo pipefail
        v="${{ inputs.version }}"

        sudo apt-get install -y "clang-${v}" "clang++-${v}" "lld-${v}"
        "/usr/bin/clang-${v}" --version

    - name: Set alternatives (clang, clang++)
      shell: bash
      run: |
        echo "--- Set alternatives ---"
        set -euo pipefail
        v="${{ inputs.version }}"

        sudo update-alternatives --install /usr/bin/clang clang "/usr/bin/clang-${v}" 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ "/usr/bin/clang++-${v}" 100

        # 既に別バージョンが登録済みの場合もあるので、明示的に選択
        sudo update-alternatives --set clang "/usr/bin/clang-${v}"
        sudo update-alternatives --set clang++ "/usr/bin/clang++-${v}"

        clang --version
