# Yamlファイルを読み込み、jsonに変換
name: Load Yaml File
description: Load Json File

inputs:
  file_path:
    description: "Target Yaml file path"
    required: true
    type: string

outputs:
  json: 
    description: "Json data"
    value: ${{ steps.set-json.outputs.json }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - id: set-json
      shell: bash
      run: |
          python3 - << 'EOF'
          import yaml, json
          from pathlib import Path

          data = yaml.safe_load(Path("${{ inputs.file_path }}").read_text(encoding="utf-8"))
          print(json.dumps(data))
          EOF
          | while read line; do
              echo "json=$line" >> "$GITHUB_OUTPUT"
            done
