name: Install GCC
description: Install GCC

inputs:
  version:
    required: false
    type: string
    default: latest
  allow_ppa:
    required: false
    default: "true" 

outputs:
  codename:
    description: "Ubuntu codename (from check-ubuntu)"
    value: ${{ steps.os.outputs.codename }}
  source:
    description: "Install source used: ubuntu or ppa"
    value: ${{ steps.decide.outputs.source }}
  gcc_bin_name:
    value: "gcc-${{ inputs.version }}"
  gxx_bin_name:
    value: "g++-${{ inputs.version }}"

runs:
  using: composite
  steps:
    - name: Check Ubuntu
      id: os
      uses: ./.github/actions/check-ubuntu

    - name: Show OS info (outputs example)
      shell: bash
      run: |
        echo "--- Show OS info ---"
        echo "id=${{ steps.os.outputs.id }}"
        echo "version_id=${{ steps.os.outputs.version_id }}"
        echo "codename=${{ steps.os.outputs.codename }}"

    - name: Decide install source (ubuntu repo or ppa)
      id: decide
      shell: bash
      run: |
        echo "--- Decide install source (ubuntu repo or ppa) ---"
        set -euo pipefail
        v="${{ inputs.version }}"

        # APT の現状構成で「実際にインストール可能か」を dry-run で判定する
        if sudo apt-get install -y -s "gcc-${v}" "g++-${v}" >/dev/null 2>&1; then
          echo "source=ubuntu" >> "$GITHUB_OUTPUT"
          echo "gcc-${v}/g++-${v} are installable from current APT sources -> use ubuntu repo"
        else
          echo "source=ppa" >> "$GITHUB_OUTPUT"
          echo "gcc-${v}/g++-${v} are NOT installable from current APT sources -> use ppa"
        fi

        # ついでにアップデートしておく
        sudo apt-get update

    - name: Setup LLVM apt repo via ppa (only if needed)
      if: ${{ steps.decide.outputs.source == 'ppa' }}
      shell: bash
      run: |
        echo "--- Setup LLVM apt repo via ppa (only if needed) ---"
        set -euo pipefail
        V="${{ inputs.version }}"
        ALLOW_PPA="${{ inputs.allow_ppa }}"

        if [ "${ALLOW_PPA}" != "true" ]; then
          echo "::error title=GCC package not found::gcc-${V}/g++-${V} not available in default repos, and allow_ppa=false."
          exit 1
        fi

        # PPA を追加
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

    - name: Install GCC/G++
      shell: bash
      run: |
        set -euo pipefail
        V="${{ inputs.version }}"
        ALLOW_PPA="${{ inputs.allow_ppa }}"

        sudo apt-get install -y "gcc-${V}" "g++-${V}"
        "/usr/bin/gcc-${V}" --version

    - name: Set alternatives (clang, clang++)
      shell: bash
      run: |
        echo "--- Set alternatives ---"
        set -euo pipefail
        V="${{ inputs.version }}"

        # gcc/g++ を指定バージョンへ切替(g++ も追随させる）
        sudo update-alternatives --install /usr/bin/gcc gcc "/usr/bin/gcc-${V}" 100 \
          --slave /usr/bin/g++ g++ "/usr/bin/g++-${V}"

        # 既に別バージョンが登録済みの場合もあるので、明示的に選択
        sudo update-alternatives --set gcc "/usr/bin/gcc-${V}"

        gcc --version
        g++ --version
